org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric properties
minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17.19
fabric_api_version=0.141.6+1.21.11
cloth_config_version=21.11.153
modmenu_version=17.0.1-beta.1

# Mod properties
version=1.0.1+mc1.21.11
group=de.unlimitedbytes
